/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SM_H_RPCGEN
#define _SM_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SM_MAXSTRLEN 1024

struct __attribute__((packed)) sm_status {
	char *sm_mon_name;
	int sm_state;
	char sm_priv[16];
};
typedef struct sm_status sm_status;

struct __attribute__((packed)) sm_name {
	char *sm_name_mon_name;
};
typedef struct sm_name sm_name;

struct __attribute__((packed)) my_id {
	char *my_name;
	int my_prog;
	int my_vers;
	int my_proc;
};
typedef struct my_id my_id;

struct __attribute__((packed)) mon_id {
	char *mon_id_name;
	struct my_id my_mon_id;
};
typedef struct mon_id mon_id;

struct __attribute__((packed)) mon {
	struct mon_id mon_id;
	char mon_priv[16];
};
typedef struct mon mon;

struct __attribute__((packed)) stat_chge {
	char *stat_chge_mon_name;
	int stat_chge_state;
};
typedef struct stat_chge stat_chge;

struct __attribute__((packed)) sm_stat {
	int sm_stat_state;
};
typedef struct sm_stat sm_stat;

enum sm_res {
	stat_succ = 0,
	stat_fail = 1,
};
typedef enum sm_res sm_res;

struct __attribute__((packed)) sm_stat_res {
	sm_res sm_res_stat;
	int sm_res_state;
};
typedef struct sm_stat_res sm_stat_res;

#define RPCPROG_SM 100024
#define SM_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SM_V1_STAT 1
extern  enum clnt_stat sm_v1_stat_1(struct sm_name *, struct sm_stat_res *, CLIENT *);
extern  bool_t sm_v1_stat_1_svc(struct sm_name *, struct sm_stat_res *, struct svc_req *);
#define SM_V1_MON 2
extern  enum clnt_stat sm_v1_mon_1(struct mon *, struct sm_stat_res *, CLIENT *);
extern  bool_t sm_v1_mon_1_svc(struct mon *, struct sm_stat_res *, struct svc_req *);
#define SM_V1_UNMON 3
extern  enum clnt_stat sm_v1_unmon_1(struct mon_id *, struct sm_stat *, CLIENT *);
extern  bool_t sm_v1_unmon_1_svc(struct mon_id *, struct sm_stat *, struct svc_req *);
#define SM_V1_UNMON_ALL 4
extern  enum clnt_stat sm_v1_unmon_all_1(struct my_id *, struct sm_stat *, CLIENT *);
extern  bool_t sm_v1_unmon_all_1_svc(struct my_id *, struct sm_stat *, struct svc_req *);
#define SM_V1_SIMU_CRASH 5
extern  enum clnt_stat sm_v1_simu_crash_1(void *, void *, CLIENT *);
extern  bool_t sm_v1_simu_crash_1_svc(void *, void *, struct svc_req *);
#define SM_V1_NOTIFY 6
extern  enum clnt_stat sm_v1_notify_1(struct stat_chge *, void *, CLIENT *);
extern  bool_t sm_v1_notify_1_svc(struct stat_chge *, void *, struct svc_req *);
extern int rpcprog_sm_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SM_V1_STAT 1
extern  enum clnt_stat sm_v1_stat_1();
extern  bool_t sm_v1_stat_1_svc();
#define SM_V1_MON 2
extern  enum clnt_stat sm_v1_mon_1();
extern  bool_t sm_v1_mon_1_svc();
#define SM_V1_UNMON 3
extern  enum clnt_stat sm_v1_unmon_1();
extern  bool_t sm_v1_unmon_1_svc();
#define SM_V1_UNMON_ALL 4
extern  enum clnt_stat sm_v1_unmon_all_1();
extern  bool_t sm_v1_unmon_all_1_svc();
#define SM_V1_SIMU_CRASH 5
extern  enum clnt_stat sm_v1_simu_crash_1();
extern  bool_t sm_v1_simu_crash_1_svc();
#define SM_V1_NOTIFY 6
extern  enum clnt_stat sm_v1_notify_1();
extern  bool_t sm_v1_notify_1_svc();
extern int rpcprog_sm_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sm_status (XDR *, sm_status*);
extern  bool_t xdr_sm_name (XDR *, sm_name*);
extern  bool_t xdr_my_id (XDR *, my_id*);
extern  bool_t xdr_mon_id (XDR *, mon_id*);
extern  bool_t xdr_mon (XDR *, mon*);
extern  bool_t xdr_stat_chge (XDR *, stat_chge*);
extern  bool_t xdr_sm_stat (XDR *, sm_stat*);
extern  bool_t xdr_sm_res (XDR *, sm_res*);
extern  bool_t xdr_sm_stat_res (XDR *, sm_stat_res*);

#else /* K&R C */
extern bool_t xdr_sm_status ();
extern bool_t xdr_sm_name ();
extern bool_t xdr_my_id ();
extern bool_t xdr_mon_id ();
extern bool_t xdr_mon ();
extern bool_t xdr_stat_chge ();
extern bool_t xdr_sm_stat ();
extern bool_t xdr_sm_res ();
extern bool_t xdr_sm_stat_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SM_H_RPCGEN */
